name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile.user ./Dockerfile
    
    - name: Prepare env file
      run: echo 'NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}}' >> ./apps/user-app/.env && echo 'NEXT_PUBLIC_SECRET=${{secrets.NEXT_PUBLIC_SECRET}}' >> ./apps/user-app/.env && echo 'NEXT_PUBLIC_HELLO=${{secrets.HELLO}}' >> ./apps/user-app/.env

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: amanlalwani/wallet-app:latest

    - name: Verify Pushed Image
      run: docker pull amanlalwani/wallet-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker image remove amanlalwani/wallet-app:latest
          sudo docker pull amanlalwani/wallet-app:latest
          sudo docker run -d --name web-app   -p 3005:3000 amanlalwani/wallet-app:latest